# SPDX-FileCopyrightText: 2024 Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "polls"
SPDX-PackageSupplier = "Nextcloud <info@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/polls"

[[annotations]]
path = [".gitattributes", ".github/CODEOWNERS", "package-lock.json", "package.json", "composer.json", "composer.lock", "**/composer.json", "**/composer.lock", ".l10nignore", "cypress/tsconfig.json", "vendor-bin/**/composer.json", "vendor-bin/**/composer.lock", ".tx/config", "tsconfig.json", "js/vendor.LICENSE.txt", "krankerl.toml", ".npmignore", ".eslintrc.json", ".tx/backport"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["l10n/**.js", "l10n/**.json", "js/**.js.map", "js/**.js", "js/**.mjs", "js/**.mjs.map", "js/templates/**.handlebars", "emptyTemplates/**", "jsconfig.json", "img/app.svg", "img/polls.svg", "img/polls-dark.svg", "src/assets/icons/maybe-vote.svg", "src/assets/icons/no-vote.svg", "src/assets/icons/spinner.svg", "src/assets/icons/yes-vote.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["screenshots/edit-poll.png", "screenshots/overview.png", "screenshots/share.png", "screenshots/vote.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Nextcloud contributors"
SPDX-License-Identifier = "CC0-1.0"
